### ISSUE TITLE
Seas of blood picture support implementation

### ISSUE THREAD

**Issue by angstsmurf** [EtchedPixels/TaylorMade#1]
I don't if there is still any interest in this repo, but in case anyone feels like working on picture support, there is a full implementation of the closely related Seas of Blood image drawing in the Spatterlight repo [here](https://github.com/angstsmurf/spatterlight/blob/master/terps/scott/seasofblood.c#L172-L222).

**Comment by EtchedPixels** [comment]
Interesting that someone went to all that trouble. It looks pretty much how I remember it working (I wrote some of the original one 8)). They are very similar for the games from that point on. Robin of Sherwood was 'special', but the games after pretty much used the same set up for the 8bit era. The pre RoS games are very similar too as the block encoding is taken from the picture encoding in the older games.

Not something I personally have time to dig into much.

**Comment by angstsmurf** [comment]
Yes, all the earlier versions are working. I made a small video here: https://youtu.be/p5Oelhsmzco.

Currently I'm hacking away at the later games, but the differences are big enough that I haven't gotten very far.

EDIT: One question: In the [FORMAT](https://github.com/EtchedPixels/TaylorMade/blob/30170574c649714234a64cea6c5a39abc6a1c287/FORMAT#L88-L120) file, there are some notes on the image format. There are a bunch of memory addresses listed there. You don't happen to remember which game they refer to?

**Comment by angstsmurf** [comment]
The graphics seem to work now, at least in Temple of Terror. The non-graphics parts are still a bit rough.

https://github.com/angstsmurf/spatterlight/blob/33cc71faf193f9d578eacc5fb1db3ca52de7fa7c/terps/taylor/sagadraw.c#L930-L1033
<img width="1042" alt="Skärmavbild 2022-03-17 kl  20 44 09" src="https://user-images.githubusercontent.com/5066755/158883204-a8bc5d9e-7ac1-430f-a8a8-63909161588f.png">

**Comment by angstsmurf** [comment]
I'll close this now. A full drawing implementation is here:
https://github.com/garglk/garglk/blob/54b8c784daf3d0a6507b8188919bf907fbe7dd4a/terps/taylor/sagadraw.c#L1050-L1169
